version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db_dumps:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 431w
      MYSQL_DATABASE: inventorymgmt
      MYSQL_ENTRYPOINT_INITDB: ./mysql/docker-entrypoint-initdb.d
      TZ: 'America/New_York'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=431w --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - internal
  web:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
    networks:
      - internal
    depends_on:
      - db

networks:
  internal:

volumes:
  db:
