import MySQLdb
from faker import Faker
fake = Faker()

import MySQLdb

db = MySQLdb.connect("localhost", "root", "431w", "inventorymgmt")
c = db.cursor()

# DATA FROM https://www.mockaroo.com/mock_apis
# AND https://www.opensecrets.org/industries/alphalist.php

def fake_warehouse():
    name = fake.company()
    c.execute("""
        INSERT INTO warehouses (name) VALUES (%s)
    """, (name,))

def fake_sector():
    name = fake.random_choices(
        elements=(
            "Accountants",
            "Advertising/Public Relations",
            "Aerospace, Defense Contractors",
            "Agribusiness",
            "Agricultural Services & Products",
            "Agriculture",
            "Air Transport",
            "Air Transport Unions",
            "Airlines",
            "Alcoholic Beverages",
            "Alternative Energy Production & Services",
            "Architectural Services",
            "Attorneys/Law Firms",
            "Auto Dealers",
            "Auto Dealers, Japanese",
            "Auto Manufacturers",
            "Automotive",
            "Banking, Mortgage",
            "Banks, Commercial",
            "Banks, Savings & Loans",
            "Bars & Restaurants",
            "Beer, Wine & Liquor",
            "Books, Magazines & Newspapers",
            "Broadcasters, Radio/TV",
            "Builders/General Contractors",
            "Builders/Residential",
            "Building Materials & Equipment",
            "Building Trade Unions",
            "Business Associations",
            "Business Services",
            "Cable & Satellite TV Production & Distribution",
            "Candidate Committees",
            "Candidate Committees, Democratic",
            "Candidate Committees, Republican",
            "Car Dealers",
            "Car Dealers, Imports",
            "Car Manufacturers",
            "Casinos / Gambling",
            "Cattle Ranchers/Livestock",
            "Chemical & Related Manufacturing",
            "Chiropractors",
            "Civil Servants/Public Officials",
            "Clergy & Religious Organizations",
            "Clothing Manufacturing",
            "Coal Mining",
            "Colleges, Universities & Schools",
            "Commercial Banks",
            "Commercial TV & Radio Stations",
            "Communications/Electronics",
            "Computer Software",
            "Conservative/Republican",
            "Construction",
            "Construction Services",
            "Construction Unions",
            "Credit Unions",
            "Crop Production & Basic Processing",
            "Cruise Lines",
            "Cruise Ships & Lines",
            "Dairy",
            "Defense",
            "Defense Aerospace",
            "Defense Electronics",
            "Defense/Foreign Policy Advocates",
            "Dentists",
            "Doctors & Other Health Professionals",
            "Drug Manufacturers",
            "Education",
            "Electric Utilities",
            "Electronics Manufacturing & Equipment",
            "Electronics, Defense Contractors",
            "Energy & Natural Resources",
            "Entertainment Industry",
            "Environment",
            "Farm Bureaus",
            "Farming",
            "Finance / Credit Companies",
            "Finance, Insurance & Real Estate",
            "Food & Beverage",
            "Food Processing & Sales",
            "Food Products Manufacturing",
            "Food Stores",
            "For-profit Education",
            "For-profit Prisons",
            "Foreign & Defense Policy",
            "Forestry & Forest Products",
            "Foundations, Philanthropists & Non-Profits",
            "Funeral Services",
            "Gambling & Casinos",
            "Gambling, Indian Casinos",
            "Garbage Collection/Waste Management",
            "Gas & Oil",
            "General Contractors",
            "Government Employees",
            "Health",
            "Health Professionals",
            "Health Services/HMOs",
            "Hedge Funds",
            "HMOs & Health Care Services",
            "Home Builders",
            "Hospitals & Nursing Homes",
            "Hotels, Motels & Tourism",
            "Indian Gaming",
            "Industrial Unions",
            "Insurance",
            "Internet",
            "Labor",
            "Lawyers & Lobbyists",
            "Lawyers / Law Firms",
            "Leadership PACs",
            "Liquor, Wine & Beer",
            "Livestock",
            "Lobbyists",
            "Lodging / Tourism",
            "Logging, Timber & Paper Mills",
            "Manufacturing, Misc",
            "Marine Transport",
            "Meat processing & products",
            "Medical Supplies",
            "Mining",
            "Misc Business",
            "Misc Finance",
            "Misc Manufacturing & Distributing",
            "Misc Unions",
            "Miscellaneous Defense",
            "Miscellaneous Services",
            "Mortgage Bankers & Brokers",
            "Motion Picture Production & Distribution",
            "Music Production",
            "Natural Gas Pipelines",
            "Newspaper, Magazine & Book Publishing",
            "Non-profits, Foundations & Philanthropists",
            "Nurses",
            "Nursing Homes/Hospitals",
            "Nutritional & Dietary Supplements",
            "Oil & Gas",
            "Other",
            "Payday Lenders",
            "Pharmaceutical Manufacturing",
            "Pharmaceuticals / Health Products",
            "Phone Companies",
            "Physicians & Other Health Professionals",
            "Postal Unions",
            "Poultry & Eggs",
            "Power Utilities",
            "Printing & Publishing",
            "Private Equity & Investment Firms",
            "Professional Sports, Sports Arenas & Related Equipment & Services",
            "Public Employees",
            "Public Sector Unions",
            "Publishing & Printing",
            "Radio/TV Stations",
            "Railroads",
            "Real Estate",
            "Record Companies/Singers",
            "Recorded Music & Music Production",
            "Recreation / Live Entertainment",
            "Residential Construction",
            "Restaurants & Drinking Establishments",
            "Retail Sales",
            "Retired",
            "Savings & Loans",
            "Schools/Education",
            "Sea Transport",
            "Securities & Investment",
            "Special Trade Contractors",
            "Sports, Professional",
            "Steel Production",
            "Stock Brokers/Investment Industry",
            "Student Loan Companies",
            "Sugar Cane & Sugar Beets",
            "Teachers Unions",
            "Teachers/Education",
            "Telecom Services & Equipment",
            "Telephone Utilities",
            "Textiles",
            "Timber, Logging & Paper Mills",
            "Tobacco",
            "Transportation",
            "Transportation Unions",
            "Trash Collection/Waste Management",
            "Trucking",
            "TV / Movies / Music",
            "TV Production",
            "Universities, Colleges & Schools",
            "Vegetables & Fruits",
            "Venture Capital",
            "Waste Management",
            "Wine, Beer & Liquor",

        ), length=1
    )[0]
    warehouse = fake.random_int(1, 1000)
    c.execute("""
        INSERT INTO sectors (`name`, `warehouse`) VALUES (%s, %s)
    """, (name, str(warehouse)))

def fake_pay():
    dollars_per_hour = fake.random_int(1, 1000)
    overtime_per_hour = dollars_per_hour + fake.random_int(1, 500)
    c.execute("""
        INSERT INTO employeepay (dollars_per_hour, overtime_per_hour) VALUES (%s, %s)
    """, (dollars_per_hour, overtime_per_hour))

def fake_shift():
    start_time = fake.date_time_this_decade()
    length = fake.random_int(60, 600, step=15)
    c.execute("""
        INSERT INTO employeeshifts (start_time, length_minutes) VALUES (%s, %s)
    """, (start_time, length))
    
def fake_employee():
    name = fake.name()
    warehouse = fake.random_int(1, 1000)
    pay = fake.random_int(1, 500)
    c.execute("""
        INSERT INTO employees (name, warehouse, pay) VALUES (%s, %s, %s)
    """, (name, warehouse, pay))

def fake_product():
    name = fake.random_choices(
        elements=(
            "Yoghurt Tubes",
            "Lentils - Green, Dry",
            "Wine - Chateau Aqueria Tavel",
            "Arizona - Green Tea",
            "Instant Coffee",
            "Placemat - Scallop, White",
            "Dry Ice",
            "Salmon - Atlantic, Skin On",
            "Chicken - White Meat, No Tender",
            "Lighter - Bbq",
            "Capicola - Hot",
            "Beer - Camerons Cream Ale",
            "Wanton Wrap",
            "Cocoa Powder - Dutched",
            "Pie Box - Cello Window 2.5",
            "Olives - Morracan Dired",
            "Foie Gras",
            "Wine - Prosecco Valdobiaddene",
            "Bread - French Baquette",
            "Bread - Raisin Walnut Oval",
            "Oven Mitts 17 Inch",
            "Cheese - Taleggio D.o.p.",
            "Wine La Vielle Ferme Cote Du",
            "Bouq All Italian - Primerba",
            "Juice - Lagoon Mango",
            "Beer - Mill St Organic",
            "Pastry - Key Limepoppy Seed Tea",
            "Beans - Kidney, Canned",
            "Vinegar - Balsamic",
            "Cheese - Brick With Onion",
            "Tomatoes - Grape",
            "Onion Powder",
            "Apricots Fresh",
            "Cheese Cloth No 100",
            "Juice - Clam, 46 Oz",
            "Pail For Lid 1537",
            "Meldea Green Tea Liquor",
            "Vinegar - Sherry",
            "Rum - Dark, Bacardi, Black",
            "C - Plus, Orange",
            "Pumpkin - Seed",
            "Beans - Black Bean, Canned",
            "Tea - Apple Green Tea",
            "Bread - Calabrese Baguette",
            "Pants Custom Dry Clean",
            "Bagelers - Cinn / Brown Sugar",
            "Chinese Lemon Pork",
            "Soup - Cream Of Broccoli, Dry",
            "Creme De Menthe Green",
            "Towel Dispenser",
            "Oil - Canola",
            "Cod - Black Whole Fillet",
            "Wine - Mas Chicet Rose, Vintage",
            "Haggis",
            "Mace",
            "Wine - Bouchard La Vignee Pinot",
            "Carbonated Water - Lemon Lime",
            "Sauce - Hp",
            "Coffee - French Vanilla Frothy",
            "Glass - Juice Clear 5oz 55005",
            "Broom - Angled",
            "Pepper - Red Bell",
            "Coke - Diet, 355 Ml",
            "Broom - Angled",
            "Beef - Baby, Liver",
            "Pepper - White, Whole",
            "Cocoa Butter",
            "Huck White Towels",
            "Nantucket - Kiwi Berry Cktl.",
            "The Pop Shoppe - Grape",
            "Oil - Shortening - All - Purpose",
            "Table Cloth 144x90 White",
            "Cheese - Fontina",
            "Nacho Chips",
            "Bread - Roll, Soft White Round",
            "Veal - Insides, Grains",
            "Bagelers - Cinn / Brown Sugar",
            "Beer - Alexander Kieths, Pale Ale",
            "Wine - Masi Valpolocell",
            "Pork - Smoked Back Bacon",
            "Beef - Striploin Aa",
            "Soup Campbells Split Pea And Ham",
            "Tray - 12in Rnd Blk",
            "Pork - Caul Fat",
            "Fennel - Seeds",
            "Cookies - Englishbay Chochip",
            "Wine - Chablis J Moreau Et Fils",
            "Cheese - Havarti, Salsa",
            "Wine - White, Riesling, Semi - Dry",
            "Lamb - Loin Chops",
            "Wine - Delicato Merlot",
            "Soup - Knorr, Veg / Beef",
            "Pheasants - Whole",
            "Onions Granulated",
            "Table Cloth - 53x69 Colour",
            "Lobster - Canned Premium",
            "Cheese - Cambozola",
            "Dc Hikiage Hira Huba",
            "Juice - Tomato, 10 Oz",
            "Pasta - Fettuccine, Egg, Fresh",
            "Ice Cream Bar - Oreo Sandwich",
            "Pork - Belly Fresh",
            "Rice Pilaf, Dry,package",
            "Cookies - Fortune",
            "Bagel - Sesame Seed Presliced",
            "Appetizer - Sausage Rolls",
            "Papayas",
            "Broom And Brush Rack Black",
            "Sugar - Invert",
            "Instant Coffee",
            "Butter Ripple - Phillips",
            "Dried Peach",
            "Quail - Eggs, Fresh",
            "Capicola - Hot",
            "Tumeric",
            "Wine - Casillero Del Diablo",
            "Wanton Wrap",
            "Calypso - Strawberry Lemonade",
            "Catfish - Fillets",
            "Juice - Pineapple, 341 Ml",
            "Chips - Assorted",
            "Tamarind Paste",
            "Peppercorns - Pink",
            "Chicken - White Meat, No Tender",
            "Vinegar - Cider",
            "Pie Shell - 9",
            "Corn Kernels - Frozen",
            "Pastry - Trippleberry Muffin - Mini",
            "Lettuce - Boston Bib",
            "Chilli Paste, Ginger Garlic",
            "Chicken Breast Wing On",
            "Milk 2% 500 Ml",
            "Chef Hat 25cm",
            "Butter - Salted, Micro",
            "Cream - 10%",
            "Trout - Smoked",
            "Goat - Whole Cut",
            "Table Cloth 54x54 Colour",
            "Lemonade - Natural, 591 Ml",
            "Cleaner - Bleach",
            "Salmon - Smoked, Sliced",
            "Godiva White Chocolate",
            "Pumpkin",
            "Bread - Hamburger Buns",
            "Coffee - Flavoured",
            "Nut - Pumpkin Seeds",
            "Juice - Cranberry 284ml",
            "Pectin",
            "Pastry - Apple Muffins - Mini",
            "Mushroom - Portebello",
            "Frangelico",
            "Kaffir Lime Leaves",
            "Orange - Blood",
            "Rabbit - Legs",
            "Wine - Two Oceans Sauvignon",
            "Pail For Lid 1537",
            "Clams - Littleneck, Whole",
            "Lotus Leaves",
            "Ocean Spray - Kiwi Strawberry",
            "Cookies Almond Hazelnut",
            "Liners - Baking Cups",
            "Muffin Hinge - 211n",
            "Tea Leaves - Oolong",
            "Steampan - Lid For Half Size",
            "Creme De Cacao White",
            "Sobe - Green Tea",
            "Vinegar - Balsamic",
            "Apple - Macintosh",
            "Soup - Knorr, Country Bean",
            "Capicola - Hot",
            "Wine - Red Oakridge Merlot",
            "Fish - Halibut, Cold Smoked",
            "Heavy Duty Dust Pan",
            "Lamb - Racks, Frenched",
            "Honey - Liquid",
            "Tea - Lemon Scented",
            "Red Cod Fillets - 225g",
            "Juice - Grape, White",
            "Water - Mineral, Carbonated",
            "Veal - Chops, Split, Frenched",
            "Tea - Decaf 1 Cup",
            "Melon - Cantaloupe",
            "Filo Dough",
            "Corn - Mini",
            "Wine - Segura Viudas Aria Brut",
            "Onions - Spanish",
            "Yoplait Drink",
            "Nut - Walnut, Pieces",
            "Cookies - Englishbay Wht",
            "Arizona - Plum Green Tea",
            "Yokaline",
            "Island Oasis - Ice Cream Mix",
            "Soup - Campbells Beef Strogonoff",
            "Pan Grease",
            "Savory",
            "Pear - Halves",
            "Pepper - Scotch Bonnet",
            "Butter Ripple - Phillips",
            "Flour - All Purpose",
            "Tarragon - Fresh",
            "Crackers - Graham",
            "Curry Powder Madras",
            "Pastry - Trippleberry Muffin - Mini",
            "Pork - Inside",
            "Green Scrubbie Pad H.duty",
            "Orange Roughy 6/8 Oz",
            "Trout Rainbow Whole",
            "Cookie Dough - Chunky",
            "Bread - Bistro Sour",
            "Cookie Dough - Oatmeal Rasin",
            "Wine - Fontanafredda Barolo",
            "Bread - Mini Hamburger Bun",
            "Mustard - Seed",
            "Pasta - Cappellini, Dry",
            "Wine - Cava Aria Estate Brut",
            "Anisette - Mcguiness",
            "Samosa - Veg",
            "Coffee - Beans, Whole",
            "Chutney Sauce",
            "Lettuce - Curly Endive",
            "Cheese - Havarti, Roasted Garlic",
            "Lettuce - Sea / Sea Asparagus",
            "Wine - Vouvray Cuvee Domaine",
            "Tea - Decaf Lipton",
            "Pork - Ground",
            "Nut - Hazelnut, Whole",
            "Broom And Brush Rack Black",
            "Pickerel - Fillets",
            "Jam - Raspberry",
            "Cheese - Taleggio D.o.p.",
            "Oyster - In Shell",
            "Appetizer - Shrimp Puff",
            "Cleaner - Pine Sol",
            "Bread - Rye",
            "Beer - Mill St Organic",
            "Cheese - Ricotta",
            "Bread - Wheat Baguette",
            "Pasta - Tortellini, Fresh",
            "Flax Seed",
            "Wine - Sogrape Mateus Rose",
            "Persimmons",
            "Quail - Jumbo Boneless",
            "Soup - Knorr, Chicken Gumbo",
            "Asparagus - White, Fresh",
            "Spinach - Packaged",
            "Chicken - Livers",
            "Wine - White, Pinot Grigio",
            "Sultanas",
            "Pears - Anjou",
            "Pork - Bacon, Double Smoked",
            "Sprouts - Brussel",
            "Shrimp - 100 / 200 Cold Water",
            "Goulash Seasoning",
            "Wine La Vielle Ferme Cote Du",
            "Veal - Osso Bucco",
            "Lentils - Red, Dry",
            "Soup - Clam Chowder, Dry Mix",
            "Island Oasis - Wildberry",
            "Wine - White, Gewurtzraminer",
            "Table Cloth 90x90 Colour",
            "Tea - Mint",
            "Pears - Bosc",
            "Cookies - Amaretto",
            "Sprouts - Peppercress",
            "Lamb Shoulder Boneless Nz",
            "Mustard - Dry, Powder",
            "Sauce - Sesame Thai Dressing",
            "Scrubbie - Scotchbrite Hand Pad",
            "Pastry - Raisin Muffin - Mini",
            "Croissants Thaw And Serve",
            "Pepper - Red Bell",
            "Ecolab - Medallion",
            "Aromat Spice / Seasoning",
            "Wine - Chateau Bonnet",
            "Jameson Irish Whiskey",
            "Squash - Sunburst",
            "Wine - Valpolicella Masi",
            "Melon - Watermelon, Seedless",
            "Raisin - Golden",
            "Trout - Rainbow, Frozen",
            "Smoked Paprika",
            "Island Oasis - Raspberry",
            "Energy Drink Bawls",
            "Napkin - Cocktail,beige 2 - Ply",
            "Fond - Chocolate",
            "Mangostein",
            "C - Plus, Orange",
            "Water Chestnut - Canned",
            "Horseradish Root",
            "Carbonated Water - White Grape",
            "Wine - White, Ej Gallo",
            "Banana - Green",
            "Water - Mineral, Carbonated",
            "Lettuce - Romaine",
            "Tea - Apple Green Tea",
            "Curry Paste - Madras",
            "Apricots Fresh",
            "Corn - Cream, Canned",
            "Sambuca - Opal Nera",
            "Milk - Skim",
            "Wine - Magnotta, White",
            "Beer - Guiness",
            "Ice Cream - Chocolate",
            "Lidsoupcont Rp12dn",
            "Cinnamon Buns Sticky",
            "Chickensplit Half",
            "Bread - Crusty Italian Poly",
            "Container Clear 8 Oz",
            "Bread - Pita, Mini",
            "Nantucket Cranberry Juice",
            "Sauce - White, Mix",
            "Mints - Striped Red",
            "Rabbit - Whole",
            "Saskatoon Berries - Frozen",
            "Wine - Zinfandel California 2002",
            "Beef - Cow Feet Split",
            "Onions Granulated",
            "Bread - Frozen Basket Variety",
            "Pomello",
            "Vermacelli - Sprinkles, Assorted",
            "Oranges",
            "Compound - Orange",
            "Cheese - Gouda",
            "Oil - Truffle, White",
            "External Supplier",
            "Cheese - Goat With Herbs",
            "Gherkin - Sour",
            "Chinese Foods - Pepper Beef",
            "Red Snapper - Fresh, Whole",
            "Paste - Black Olive",
            "Soup - Campbells Broccoli",
            "Carbonated Water - Peach",
            "Cocoa Butter",
            "Jolt Cola - Red Eye",
            "Shrimp - 21/25, Peel And Deviened",
            "Wine - Chianti Classica Docg",
            "Beef Tenderloin Aaa",
            "Garbag Bags - Black",
            "Sauce - Ranch Dressing",
            "Bread - White Mini Epi",
            "Cheese - Havarti, Salsa",
            "Fish - Base, Bouillion",
            "Extract - Raspberry",
            "Cookie Dough - Double",
            "Potatoes - Idaho 80 Count",
            "Wine - Barossa Valley Estate",
            "Wine - Prem Select Charddonany",
            "Squash - Pepper",
            "Stock - Beef, Brown",
            "Roe - Lump Fish, Black",
            "Pernod",
            "Juice - Orange, 341 Ml",
            "Wanton Wrap",
            "Wine - Magnotta - Cab Franc",
            "Broom Handle",
            "Pepper - Black, Crushed",
            "Monkfish Fresh - Skin Off",
            "Lamb - Loin Chops",
            "Crab - Meat Combo",
            "External Supplier",
            "Potatoes - Fingerling 4 Oz",
            "Shopper Bag - S - 4",
            "Stock - Beef, White",
            "Chicken - Soup Base",
            "Wine - Marlbourough Sauv Blanc",
            "Tart Shells - Savory, 2",
            "Oil - Safflower",
            "Rosemary - Fresh",
            "Lemon Balm - Fresh",
            "Coffee - Ristretto Coffee Capsule",
            "Rice Pilaf, Dry,package",
            "Wine - White, Cooking",
            "Cocoa Butter",
            "Compound - Rum",
            "Cheese - Swiss",
            "Chick Peas - Dried",
            "Wine - Touraine Azay - Le - Rideau",
            "Lettuce - Mini Greens, Whole",
            "Roe - Flying Fish",
            "Wine - Tribal Sauvignon",
            "Ginger - Pickled",
            "Corn Meal",
            "Mix - Cocktail Ice Cream",
            "Crab - Meat Combo",
            "Syrup - Monin, Swiss Choclate",
            "Cheese - Wine",
            "Cranberry Foccacia",
            "Cherries - Bing, Canned",
            "Appetizer - Mushroom Tart",
            "Cup - 8oz Coffee Perforated",
            "Ecolab - Medallion",
            "Chocolate Bar - Reese Pieces",
            "Pasta - Lasagna, Dry",
            "Mushroom - Portebello",
            "Cheese - Cream Cheese",
            "Pepper - Cayenne",
            "Soup - French Can Pea",
            "Wine - Montecillo Rioja Crianza",
            "Cheese - Camembert",
            "Coffee - 10oz Cup 92961",
            "Pie Shell - 9",
            "Leeks - Large",
            "Cookies - Fortune",
            "Mangoes",
            "Lotus Rootlets - Canned",
            "Coffee - Ristretto Coffee Capsule",
            "Soup - Campbells",
            "Pork - Loin, Boneless",
            "Nectarines",
            "Pork Casing",
            "Cheese - Parmesan Cubes",
            "Thyme - Fresh",
            "Doilies - 7, Paper",
            "True - Vue Containers",
            "Coffee Guatemala Dark",
            "Buffalo - Tenderloin",
            "Beer - Mcauslan Apricot",
            "Foie Gras",
            "Pepper - Cubanelle",
            "Southern Comfort",
            "Cheese - Brie Roitelet",
            "Buffalo - Striploin",
            "Cheese - Perron Cheddar",
            "Wine - White, Mosel Gold",
            "Lemon Tarts",
            "Chicken Breast Wing On",
            "Yogurt - French Vanilla",
            "Towels - Paper / Kraft",
            "Rice - Basmati",
            "Brownies - Two Bite, Chocolate",
            "Loaf Pan - 2 Lb, Foil",
            "Chef Hat 20cm",
            "Plate Pie Foil",
            "Garam Masala Powder",
            "Container - Clear 32 Oz",
            "Flavouring - Rum",
            "Coffee Cup 16oz Foam",
            "Ezy Change Mophandle",
            "Salt - Table",
            "Lamb - Rack",
            "Pasta - Ravioli",
            "Appetizer - Sausage Rolls",
            "Smoked Paprika",
            "Longos - Lasagna Beef",
            "Pear - Prickly",
            "Cookies Oatmeal Raisin",
            "Peas - Frozen",
            "Quail - Eggs, Fresh",
            "Wine - Piper Heidsieck Brut",
            "Wine - Jaboulet Cotes Du Rhone",
            "Bag - Clear 7 Lb",
            "Mortadella",
            "Sherry - Dry",
            "Beef Wellington",
            "Wine - Sake",
            "Sage - Fresh",
            "Nantucket - Pomegranate Pear",
            "Cheese - Brie Roitelet",
            "Lentils - Green Le Puy",
            "Eggplant - Asian",
            "Pork - Loin, Bone - In",
            "Wine - Maipo Valle Cabernet",
            "Tuna - Sushi Grade",
            "Pepper - Orange",
            "Vinegar - Raspberry",
            "Praline Paste",
            "Cookies - Oreo, 4 Pack",
            "Sherbet - Raspberry",
            "Brandy - Orange, Mc Guiness",
            "Bread - Hot Dog Buns",
            "Anchovy Paste - 56 G Tube",
            "Turkey Leg With Drum And Thigh",
            "Cheese - Le Cheve Noir",
            "Bread Country Roll",
            "Pasta - Orecchiette",
            "Stock - Beef, White",
            "Wooden Mop Handle",
            "Beer - Guiness",
            "Coffee - Irish Cream",
            "Chicken - Whole",
            "Oil - Olive Bertolli",
            "Foam Dinner Plate",
            "Hot Choc Vending",
            "Puree - Mocha",
            "Vaccum Bag 10x13",
            "Thermometer Digital",
            "Truffle Shells - White Chocolate",
            "Ice Cream - Fudge Bars",
            "Iced Tea - Lemon, 340ml",
            "Pomegranates",
            "Beer - Sleemans Honey Brown",
            "Turkey - Whole, Fresh",
            "Chocolate Liqueur - Godet White",
            "Turkey - Breast, Bone - In",
            "Rosemary - Fresh",
            "Parsnip",
            "Pastry - Cherry Danish - Mini",
            "Chinese Foods - Plain Fried Rice",
            "Wine - Piper Heidsieck Brut",
            "Energy - Boo - Koo",
            "Beans - French",
            "Cocoa Powder - Dutched",
            "Wine - Red, Black Opal Shiraz",
            "Island Oasis - Ice Cream Mix",
            "Schnappes Peppermint - Walker",
            "Pie Shells 10",
            "Muffin Batt - Choc Chk",
            "Veal Inside - Provimi",
            "Bread - French Stick",
            "Spaghetti Squash",
            "Beef Cheek Fresh",
            "Ice Cream - Life Savers",
            "Scallops - In Shell",
            "Wine - Chenin Blanc K.w.v.",
            "Wine - Red, Black Opal Shiraz",
            "Soy Protein",
            "Eggplant Oriental",
            "Garlic - Primerba, Paste",
            "Juice - Lagoon Mango",
            "The Pop Shoppe - Cream Soda",
            "Wine - White, French Cross",
            "Cocoa Feuilletine",
            "Oranges - Navel, 72",
            "Veal - Ground",
            "Cheese - Cheddar With Claret",
            "Baking Powder",
            "Magnotta - Bel Paese White",
            "Appetiser - Bought",
            "Wine - White, Colubia Cresh",
            "Wine - Delicato Merlot",
            "Schnappes - Peach, Walkers",
            "Pate - Liver",
            "Lettuce Romaine Chopped",
            "Fish - Base, Bouillion",
            "Skewers - Bamboo",
            "Pectin",
            "Curry Powder Madras",
            "Veal - Provimi Inside",
            "Cheese - Cheddar, Old White",
            "Foam Cup 6 Oz",
            "Wine - Jackson Triggs Okonagan",
            "Sauce - Cranberry",
            "Beef - Tenderloin Tails",
            "Chilli Paste, Ginger Garlic",
            "Stock - Beef, White",
            "Hinge W Undercut",
            "Bread - Frozen Basket Variety",
            "Silicone Parch. 16.3x24.3",
            "Arctic Char - Fillets",
            "Radish",
            "Wine - Magnotta - Bel Paese White",
            "Extract - Lemon",
            "Juice - Orangina",
            "Cup - Translucent 7 Oz Clear",
            "Mussels - Cultivated",
            "Chips Potato Reg 43g",
            "Appetizer - Sausage Rolls",
            "Onions - White",
            "C - Plus, Orange",
            "Pork - Back Ribs",
            "Dc - Sakura Fu",
            "Turkey - Breast, Bone - In",
            "Vegetable - Base",
            "Nutmeg - Ground",
            "Venison - Ground",
            "Wine - White, Colubia Cresh",
            "Pork - Back Ribs",
            "Quail Eggs - Canned",
            "Sambuca - Opal Nera",
            "Melon - Watermelon, Seedless",
            "Yeast Dry - Fermipan",
            "Grapefruit - Pink",
            "Devonshire Cream",
            "Celery Root",
            "Thyme - Lemon, Fresh",
            "Jam - Marmalade, Orange",
            "Tray - 12in Rnd Blk",
            "Gelatine Leaves - Bulk",
            "Fireball Whisky",
            "Wine - Riesling Alsace Ac 2001",
            "Wine - Jaboulet Cotes Du Rhone",
            "Squid - U - 10 Thailand",
            "Soup - Campbells Beef Stew",
            "Ginger - Crystalized",
            "Wine - Blue Nun Qualitatswein",
            "Sauce - Rosee",
            "Garlic",
            "Jameson - Irish Whiskey",
            "Soup - Campbells Chicken",
            "Oil - Cooking Spray",
            "Raisin - Dark",
            "Carbonated Water - Strawberry",
            "Pork - Sausage, Medium",
            "Pastry - Apple Muffins - Mini",
            "Rabbit - Whole",
            "Wine - White, Cooking",
            "Soupcontfoam16oz 116con",
            "Petit Baguette",
            "Basil - Fresh",
            "Coffee - Egg Nog Capuccino",
            "Flour - So Mix Cake White",
            "Oil - Hazelnut",
            "Appetizer - Mushroom Tart",
            "Spic And Span All Purpose",
            "Smirnoff Green Apple Twist",
            "Shichimi Togarashi Peppeers",
            "Compound - Strawberry",
            "Muffin Batt - Carrot Spice",
            "Bar Mix - Pina Colada, 355 Ml",
            "Soup - Campbellschix Stew",
            "Ham - Procutinni",
            "Table Cloth 62x114 Colour",
            "Pasta - Canelloni, Single Serve",
            "Mace",
            "Bread Roll Foccacia",
            "Juice - Prune",
            "Lobster - Cooked",
            "Nantucket - Pomegranate Pear",
            "Kiwano",
            "Pasta - Penne, Lisce, Dry",
            "Sprite - 355 Ml",
            "Corn - On The Cob",
            "Soup - Clam Chowder, Dry Mix",
            "Pail For Lid 1537",
            "Rabbit - Saddles",
            "Veal - Inside, Choice",
            "Oysters - Smoked",
            "Soup Campbells Beef With Veg",
            "Ice Cream Bar - Hageen Daz To",
            "Plasticforkblack",
            "General Purpose Trigger",
            "Nantucket Orange Juice",
            "Lamb Shoulder Boneless Nz",
            "Garlic Powder",
            "Beef - Tongue, Fresh",
            "Pork Salted Bellies",
            "Brownies - Two Bite, Chocolate",
            "Nori Sea Weed - Gold Label",
            "Tarts Assorted",
            "Chicken - Diced, Cooked",
            "Bar Mix - Lime",
            "Tia Maria",
            "Pastrami",
            "Pork - Shoulder",
            "Chocolate - Semi Sweet, Calets",
            "Munchies Honey Sweet Trail Mix",
            "Wine - Chateauneuf Du Pape",
            "Chestnuts - Whole,canned",
            "Icecream Bar - Del Monte",
            "Pepper - Black, Ground",
            "Vinegar - Cider",
            "Bag - Clear 7 Lb",
            "Kiwi",
            "Veal - Insides, Grains",
            "Veal - Chops, Split, Frenched",
            "Squid - U - 10 Thailand",
            "Container - Clear 32 Oz",
            "Sauce - Fish 25 Ozf Bottle",
            "Extract - Rum",
            "Bread - Onion Focaccia",
            "Sauce - Marinara",
            "Creamers - 10%",
            "Munchies Honey Sweet Trail Mix",
            "Beer - Rickards Red",
            "Chips Potato Reg 43g",
            "Apple - Macintosh",
            "Lid - 3oz Med Rec",
            "Tortillas - Flour, 12",
            "Turkey Leg With Drum And Thigh",
            "Pop Shoppe Cream Soda",
            "Sugar - Invert",
            "Tuna - Salad Premix",
            "True - Vue Containers",
            "Lamb - Sausage Casings",
            "Rosemary - Dry",
            "Lemons",
            "Oil - Olive, Extra Virgin",
            "Table Cloth 120 Round White",
            "Tray - 12in Rnd Blk",
            "Soup - Campbells, Beef Barley",
            "Cheese - Taleggio D.o.p.",
            "Cleaner - Bleach",
            "Grand Marnier",
            "Dill Weed - Dry",
            "Meldea Green Tea Liquor",
            "Peas - Frozen",
            "Eggplant Italian",
            "Pate - Cognac",
            "Beer - Mcauslan Apricot",
            "Juice - Orangina",
            "Tomatoes Tear Drop Yellow",
            "Chick Peas - Dried",
            "Barley - Pearl",
            "Chocolate - Mi - Amere Semi",
            "Lettuce - Iceberg",
            "Beef - Rib Eye Aaa",
            "Squid - U 5",
            "Pork Ham Prager",
            "Whmis Spray Bottle Graduated",
            "Butter Sweet",
            "Gatorade - Cool Blue Raspberry",
            "Lemonade - Black Cherry, 591 Ml",
            "Beer - Maudite",
            "Pork - Shoulder",
            "Salami - Genova",
            "Petit Baguette",
            "Ecolab - Power Fusion",
            "Asparagus - White, Canned",
            "Pasta - Fettuccine, Dry",
            "Beer - Maudite",
            "Pepsi - 600ml",
            "Cream Of Tartar",
            "Potato - Sweet",
            "Sole - Iqf",
            "Cassis",
            "Muffin Orange Individual",
            "Parasol Pick Stir Stick",
            "Beef - Diced",
            "Bread - Assorted Rolls",
            "Dawn Professionl Pot And Pan",
            "Tomatoes - Grape",
            "Trout - Rainbow, Fresh",
            "Muskox - French Rack",
            "Syrup - Pancake",
            "Foil - Round Foil",
            "Guava",
            "Butter Sweet",
            "Tomato - Green",
            "Mcgillicuddy Vanilla Schnap",
            "Melon - Honey Dew",
            "Petit Baguette",
            "Cocoa Powder - Dutched",
            "Cheese - Cheddar, Old White",
            "Ecolab - Lime - A - Way 4/4 L",
            "Tamarind Paste",
            "Flower - Leather Leaf Fern",
            "Mushroom - Chanterelle Frozen",
            "Tia Maria",
            "Shrimp, Dried, Small / Lb",
            "Muffin - Bran Ind Wrpd",
            "Limes",
            "Sun - Dried Tomatoes",
            "Bulgar",
            "Chicken Giblets",
            "Duck - Whole",
            "Veal - Insides Provini",
            "Sugar - Icing",
            "Onion - Dried",
            "Flower - Potmums",
            "Juice - Clamato, 341 Ml",
            "Soup - Campbells, Butternut",
            "Bread - Flat Bread",
            "Long Island Ice Tea",
            "Table Cloth 91x91 Colour",
            "Wine - White, Concha Y Toro",
            "Potatoes - Peeled",
            "Coffee Cup 16oz Foam",
            "Doilies - 10, Paper",
            "Cloves - Ground",
            "Soup - Knorr, Classic Can. Chili",
            "Brandy - Orange, Mc Guiness",
            "Energy - Boo - Koo",
            "Dr. Pepper - 355ml",
            "Cake - Dulce De Leche",
            "Soup - Campbellschix Stew",
            "Icecream Cone - Areo Chocolate",
            "Coffee - Frthy Coffee Crisp",
            "Wine - Prosecco Valdobienne",
            "Snapple - Mango Maddness",
            "Veal - Liver",
            "Bagel - Everything Presliced",
            "Bacardi Breezer - Strawberry",
            "Cumin - Ground",
            "Turkey - Breast, Double",
            "Smirnoff Green Apple Twist",
            "Vinegar - Red Wine",
            "Mackerel Whole Fresh",
            "Water - Mineral, Carbonated",
            "Trueblue - Blueberry",
            "Smoked Paprika",
            "Cheese - Provolone",
            "Lamb Rack Frenched Australian",
            "Red Currants",
            "Extract - Lemon",
            "Juice - Lagoon Mango",
            "Container - Foam Dixie 12 Oz",
            "Soup - Base Broth Chix",
            "Bread - White Epi Baguette",
            "Wine - Pinot Grigio Collavini",
            "Skirt - 29 Foot",
            "Carbonated Water - Cherry",
            "Isomalt",
            "Wine - Red, Concha Y Toro",
            "Cookie Trail Mix",
            "Quinoa",
            "Parasol Pick Stir Stick",
            "Compound - Rum",
            "Soup - Campbells",
            "Sobe - Liz Blizz",
            "Hand Towel",
            "Turnip - Wax",
            "Island Oasis - Banana Daiquiri",
            "Tarragon - Primerba, Paste",
            "Flower - Carnations",
            "Cake - Bande Of Fruit",
            "Tarragon - Primerba, Paste",
            "Apricots - Dried",
            "Skewers - Bamboo",
            "Table Cloth 62x114 Colour",
            "Salmon - Atlantic, Fresh, Whole",
            "Schnappes - Peach, Walkers",
            "Wine - Magnotta - Cab Franc",
            "Towel Multifold",
            "Canada Dry",
            "Beets - Golden",
            "Cheese - Blue",
            "Pasta - Agnolotti - Butternut",
            "Rice Wine - Aji Mirin",
            "Stainless Steel Cleaner Vision",
            "Mustard - Dry, Powder",
            "Pork - Backfat",
            "Glass Clear 7 Oz Xl",
            "Cleaner - Pine Sol",
            "Bread Base - Toscano",
            "Shrimp - Black Tiger 8 - 12",
            "Egg Patty Fried",
            "Trout - Hot Smkd, Dbl Fillet",
            "Beef - Top Butt Aaa",
            "Appetizer - Mango Chevre",
            "Broom And Brush Rack Black",
            "Tomato - Green",
            "Water - Perrier",
            "Sugar - Palm",
            "Hot Chocolate - Individual",
            "Pasta - Tortellini, Fresh",
            "Country Roll",
            "Cream - 10%",
            "Sauce - Oyster",
            "Juice - V8 Splash",
            "Pork - European Side Bacon",
            "Bread - Wheat Baguette",
            "Bread - Crumbs, Bulk",
            "Foil Wrap",
            "Appetizer - Lobster Phyllo Roll",
            "Flour - Strong",
            "Cup - 4oz Translucent",
            "Wine - Prosecco Valdobienne",
            "Gelatine Powder",
            "Soup - Knorr, French Onion",
            "Milk - Homo",
            "Chocolate - Semi Sweet",
            "Brandy - Orange, Mc Guiness",
            "Muffin - Blueberry Individual",
            "Lid - Translucent, 3.5 And 6 Oz",
            "Papayas",
            "Wasabi Paste",
            "Ham - Cooked Bayonne Tinned",
            "Pork - Kidney",
            "Beer - Sleemans Honey Brown",
            "Mushroom - Morels, Dry",
            "Water - Evian 355 Ml",
            "Crawfish",
            "Pasta - Bauletti, Chicken White",
            "Octopus - Baby, Cleaned",
            "Puree - Blackcurrant",
            "Coffee Cup 12oz 5342cd",
            "Ketchup - Tomato",
            "Aromat Spice / Seasoning",
            "Persimmons",
            "Pork - Backs - Boneless",
            "Myers Planters Punch",
            "Vegetable - Base",
            "Pasta - Tortellini, Fresh",
            "Dried Cherries",
            "Chives - Fresh",
            "Savory",
            "Eggplant - Baby",
            "Eggwhite Frozen",
            "Ice Cream - Super Sandwich",
            "Cheese - Le Cru Du Clocher",
            "Soupcontfoam16oz 116con",
            "Carrots - Purple, Organic",
            "Beans - Turtle, Black, Dry",
            "Ginger - Pickled",
            "Table Cloth 72x144 White",
            "Pepper - White, Ground",
            "Madeira",
            "Salt - Table",
            "Capon - Whole",
            "Chocolate - Semi Sweet",
            "Food Colouring - Green",
            "Honey - Comb",
            "Jerusalem Artichoke",
            "Trueblue - Blueberry 12x473ml",
            "Beer - Steamwhistle",
            "Potatoes - Mini White 3 Oz",
            "Pepper - Gypsy Pepper",
            "Wiberg Cure",
            "Daikon Radish",
            "Soup Campbells",
            "Muffin Batt - Ban Dream Zero",
            "Wine - Charddonnay Errazuriz",
            "Muffin - Carrot Individual Wrap",
            "Pie Filling - Pumpkin",
            "Cherries - Frozen",
            "Soup - Knorr, French Onion",
            "Potatoes - Yukon Gold, 80 Ct",
            "Juice - V8 Splash",
            "Ecolab - Lime - A - Way 4/4 L",
            "Pork - Smoked Back Bacon",
            "Lettuce - Boston Bib - Organic",
            "Yogurt - Peach, 175 Gr",
            "Tart Shells - Savory, 3",
            "Madeira",
            "Nantucket - Orange Mango Cktl",
            "Flounder - Fresh",
            "Guinea Fowl",
            "Lettuce - California Mix",
            "Cake - Pancake",
            "Rosemary - Dry",
            "Pepper - Cubanelle",
            "Wine - Magnotta, Merlot Sr Vqa",
            "Duck - Breast",
            "Bread - Italian Sesame Poly",
            "Soup - Campbells, Lentil",
            "Flavouring - Orange",
            "Milk - Buttermilk",
            "Wine - Taylors Reserve",
            "Sping Loaded Cup Dispenser",
            "Kiwi Gold Zespri",
            "Soap - Hand Soap",
            "Pop - Club Soda Can",
            "Wine - Fontanafredda Barolo",
            "Bar - Granola Trail Mix Fruit Nut",
            "Tea - Orange Pekoe",
            "Garlic",
            "Bagel - Plain",
            "Rice - Jasmine Sented",
            "Cleaner - Bleach",
            "Bandage - Fexible 1x3",
            "Oil - Cooking Spray",
            "Tofu - Soft",
            "Truffle - Whole Black Peeled",
            "Chevril",
            "Nut - Almond, Blanched, Ground",
            "Wine - Domaine Boyar Royal",
            "Grapefruit - White",
            "Ecolab Digiclean Mild Fm",
            "Carrots - Purple, Organic",
            "Blueberries - Frozen",
            "Tea - Herbal - 6 Asst",
            "Sambuca - Opal Nera",
            "Wine - White, Cooking",
            "Cheese - Mozzarella, Shredded",
            "Lettuce - Boston Bib - Organic",
            "Onions - Cooking",
            "Chicken - Ground",
            "Cranberries - Fresh",
            "Flour - Pastry",
            "Pork - Smoked Kassler",
            "Flour - Fast / Rapid",
            "Lemonade - Black Cherry, 591 Ml",
            "Brandy Cherry - Mcguinness",
            "Wine - Vovray Sec Domaine Huet",
            "Nantucket Pine Orangebanana",
            "Jerusalem Artichoke",
            "Pasta - Lasagna Noodle, Frozen",
            "Chocolate Eclairs",
            "Table Cloth 62x120 Colour",
            "Wine - Magnotta - Cab Franc",
            "Pork - Bacon, Double Smoked",
            "Mushroom - Porcini, Dry",
            "Fish - Base, Bouillion",
            "Beer - Sleemans Cream Ale",
            "Oranges - Navel, 72",
            "Flavouring - Raspberry",
            "Soupfoamcont12oz 112con",
            "Cilantro / Coriander - Fresh",
            "Lid Coffeecup 12oz D9542b",
            "Mushroom - White Button",
            "Shrimp - Black Tiger 6 - 8",
            "Bread - Sticks, Thin, Plain",
            "Compound - Passion Fruit",
            "Mortadella",
            "Beans - Kidney, Red Dry",
            "Red Snapper - Fresh, Whole",
            "Chocolate - Sugar Free Semi Choc",
            "Chick Peas - Dried",
            "Crab Brie In Phyllo",
            "Artichoke - Hearts, Canned",
            "Bagel - Everything",
            "Tomato - Green",
            "Puree - Raspberry",
            "Buffalo - Tenderloin",
            "Tomatoes - Grape",
            "Lobster - Baby, Boiled",
            "Veal - Striploin",
            "Gelatine Leaves - Envelopes",
            "Food Colouring - Pink",
            "Savory"
        ), length=1
    )[0]
    sector = fake.random_int(1, 10000)
    c.execute("""
        INSERT INTO products (name, sector) VALUES (%s, %s)
    """, (name, sector))

def fake_invtransaction():
    employee = fake.random_int(1, 100000)
    product = fake.random_int(1, 100000)
    quantity_added = fake.random_int(1, 100)
    timestamp = fake.date_time_this_decade()
    c.execute("""
        INSERT INTO inventorytransactions (employee, product, quantity_added, timestamp) VALUES (%s, %s, %s, %s)
    """, (employee, product, quantity_added, timestamp))


if __name__ == "__main__":
    for _ in range(1000):
        fake_warehouse()
    db.commit()
    print("Done with warehouses")
    for _ in range(10000):
        fake_sector()
    db.commit()
    print("Done with sectors")
    for _ in range(500):
        fake_pay()
    db.commit()
    print("Done with pay")
    for _ in range(1000):
        fake_shift()
    db.commit()
    print("Done with shifts")
    for _ in range(100000):
        fake_employee()
    db.commit()
    print("Done with employees")
    for _ in range(100000):
        fake_product()
    db.commit()
    print("Done with products")
    for _ in range(500000):
        fake_invtransaction()
    db.commit()
    print("done")
